### ISSUE TITLE
COCO and LVIS dataset preprocessing

### ISSUE THREAD

**Issue by MaureenZOU** [uncbiag/SimpleClick#10]
Hi Authors! Thanks so much for your great work : )

I have a question on how do you combine the COCO and LVIS dataset, do you replace the same mask in COCO with LVIS mask? Thanks a lot!

Best,
Xueyan

**Comment by qinliuliuqin** [comment]
Hi Xueyan, please refer to Sec. 4.2 of the [RITM paper](https://arxiv.org/pdf/2102.06583.pdf).
