### ISSUE TITLE
Click generation

### ISSUE THREAD

**Issue by Scott-che** [uncbiag/SimpleClick#12]
I want to ask how to generate clicking points?
Is using this file 'points_sampler.py' ?

**Comment by qinliuliuqin** [comment]
Yes, 'points_sampler.py' is used to generate the initial set of clicks for training. Please also refer to [this function](https://github.com/uncbiag/SimpleClick/blob/8c15f43c0816d2664dceb94f319a64b94eff629b/isegm/engine/trainer.py#L276) on how to generate clicks iteratively during training.
