### ISSUE TITLE
Flop/Memory Evaluation Code

### ISSUE THREAD

**Issue by Mingyuan1997** [uncbiag/SimpleClick#14]
Thanks for your contribution!

Could you also share FLOP/mem evaluation code about the transformer based model? It seems that there is not a common and standardlized measurement library for that.

Best

**Comment by qinliuliuqin** [comment]
Hi, thanks for your questions.

FLOPs:
https://github.com/uncbiag/SimpleClick/blob/v1.0/notebooks/analyze_effiency.ipynb

Mem: https://github.com/uncbiag/SimpleClick/blob/4099621fcfa99f2cc8a4409ea61420e016ec7920/scripts/evaluate_model.py#L142
