### ISSUE TITLE
click points

### ISSUE THREAD

**Issue by Scott-che** [uncbiag/SimpleClick#15]
Recently, I researched on interactive segmentation. I would like to ask what is the click point map format (ex: gaussaion heatmap) to feed into network.

**Comment by qinliuliuqin** [comment]
Hi, clicks are encoded as a 2-channel disk map.

**Comment by Scott-che** [comment]
Does 2-channel mean that one is positive and the other channel is negative?

**Comment by qinliuliuqin** [comment]
Yes, you are right.

**Comment by Scott-che** [comment]
Thanks a lot
