### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by Scott-che** [uncbiag/SimpleClick#16]
I try to use demo.py, so I download the pretrained weights from the link that you proposed. But I got the AssertionError.
How could I fix it?
![image](https://github.com/uncbiag/SimpleClick/assets/67545227/6ecb791d-dbea-4f65-b7f2-775255c11e85)

**Comment by Scott-che** [comment]
I also try mark out 'assert pname in model_default_params' in serialization.py, but I got another error
![image](https://github.com/uncbiag/SimpleClick/assets/67545227/e34cf41d-821e-462c-9537-4268c9cd9bdf)

**Comment by qinliuliuqin** [comment]
Hi, did you use the right branch? You should use the [branch v1.0](https://github.com/uncbiag/SimpleClick/tree/v1.0) to run the models. I am refactoring the code in the main branch.

**Comment by Scott-che** [comment]
Thank your help.
