### ISSUE TITLE
How can i add and eval_ritm  argument ?

### ISSUE THREAD

**Issue by edmundman** [uncbiag/SimpleClick#2]
Trying to run the demo and i get this error, the pth is in the main directory.

D:\Code\SimpleClick>python demo.py --checkpoint cocolvis_vit_huge.pth
Traceback (most recent call last):
  File "D:\Code\SimpleClick\demo.py", line 59, in <module>
    main()
  File "D:\Code\SimpleClick\demo.py", line 18, in main
    model = utils.load_is_model(checkpoint_path, args.device, cpu_dist_maps=True)
TypeError: load_is_model() missing 1 required positional argument: 'eval_ritm'

**Comment by qinliuliuqin** [comment]
The issue has been fixed. 
Thank you!
