### ISSUE TITLE
There is no transformer_helper in isegm.model.modeling

### ISSUE THREAD

**Issue by Damage0413** [uncbiag/SimpleClick#21]
Hello, I find that there maybe something wrong in your code
![image](https://github.com/uncbiag/SimpleClick/assets/61465908/cdbb4155-61c1-437a-9e16-0be21094e33b)
![image](https://github.com/uncbiag/SimpleClick/assets/61465908/147fc4a2-f701-4052-8d7c-cdc216dcd486)

**Comment by qinliuliuqin** [comment]
Please check out the v1.0 branch: https://github.com/uncbiag/SimpleClick/tree/v1.0/isegm/model/modeling. I am currently refactoring the code in the main branch. Sorry for the confusion.

**Comment by qinliuliuqin** [comment]
Close this issue. Free free to reopen it if you still have questions.
