### ISSUE TITLE
Is it allowed to use SimpleClick for commercial purposes?

### ISSUE THREAD

**Issue by Crazy-Tony** [uncbiag/SimpleClick#27]
I would like to fine-tune the SimpleClick model for commercial purposes. I don't know if I'm allowed to do that because different datasets were used to train the SimpleClick model.

I've seen that the backbone ViT pretrained on the ImageNet-1k dataset. The ImageNet license is custom and defines: _Researcher shall use the Database only for non-commercial research and educational purposes_.

The fine-tuning is done on the COCO + LVIS dataset. The COCO + LVIS dataset can be used for commercial purposes based on their license.

Could you please tell me if it's allowed to fine-tune and use the SimpleClick model for commercial purposes?

**Comment by Crazy-Tony** [comment]
> @Crazy-Tony Hi, thanks for your question. The MIT license does allow commercial use. However, I am not sure if this still holds when using ImageNet-1k for pretraining. I will get back to you once I know the answer.

Thank you for your reply. Would be really nice to have this question answered, there are a lot of discussions about the ImageNet dataset used for pretrained and no one seems to have the answer for the commercial usage, if the network was fine-tuned on other datasets.

**Comment by Crazy-Tony** [comment]
@qinliuliuqin Could you please tell me, if there exist SimpleClick models, where no parts of the model were pretrained on ImageNet?
In case there are no SimpleClick models, that aren't pretrained on ImageNet: How many resources would it require to train a new SimpleClick model on COCO+LVIS only, without a pretrained ViT on ImageNet?

Thanks in advance!

**Comment by qinliuliuqin** [comment]
@Crazy-Tony Hi, we only released a tiny model trained from scratch, but it was much worse than SOTA. If you want to train SimpleClick models without ImageNet pretraining, you may need to train them much longer than we did. Our huge model was trained on 4 A6000 GPUs (48G each) for about 24 hours.

**Comment by Crazy-Tony** [comment]
Thanks for your help :)
