### ISSUE TITLE
The batchsize for training SimpleClick-xTiny

### ISSUE THREAD

**Issue by ChenyiZhang007** [uncbiag/SimpleClick#33]
Hi, i didn't find this setting in the paper.

**Comment by qinliuliuqin** [comment]
https://github.com/uncbiag/SimpleClick/blob/f33112e5a37ac97b9adfb9cda0106830e77b5b7d/models/iter_mask/plainvit_xtiny448_cocolvis_itermask.py#L61

For xTiny, I used the default batch size, so the training has more iterations than ViT-Base.

**Comment by ChenyiZhang007** [comment]
thanks a lot
