### ISSUE TITLE
inference performance tunning

### ISSUE THREAD

**Issue by xbkaishui** [uncbiag/SimpleClick#8]
hello,  thanks for you great work.  I want to enhance the model inference performance, can you give some advices. 
below is some ideas I want to try: 

- use FP16
- change the input image size to small 

is that ok ?

**Comment by qinliuliuqin** [comment]
Yes, if you want to improve the speed/memory of SimpleClick, you can use a smaller input size (e.g., 224x224). Using FP16 should also be helpful.

**Comment by xbkaishui** [comment]
ok. so how to find the smaller model? do you mean just change the input size
